---
deployment:
 tasks:
 - export DEPLOYPATH=/home/azle/public_html/api
 - /bin/cp -r dist $DEPLOYPATH
 - /bin/cp -r src $DEPLOYPATH
 - /bin/cp ormconfig.ts $DEPLOYPATH
 - /bin/cp package.json $DEPLOYPATH
 - /bin/cp package-lock.json $DEPLOYPATH
 - /bin/cp nest-cli.json $DEPLOYPATH
 - forever restart -c "node --max_old_space_size=8192" $DEPLOYPATH/dist/src/main.js